services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ~/.config/gcloud/application_default_credentials.json:/creds.json
    environment:
      # using relaxed bindings
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/demo
      SPRING_DATASOURCE_USERNAME: demo
      SPRING_DATASOURCE_PASSWORD: demo
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 11
      SERVER_PORT: 8080

      # for Google Cloud ADC
      GOOGLE_APPLICATION_CREDENTIALS: /creds.json
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
    driver: local